/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiKeysPost200ResponseData } from './ApiKeysPost200ResponseData';
import {
    ApiKeysPost200ResponseDataFromJSON,
    ApiKeysPost200ResponseDataFromJSONTyped,
    ApiKeysPost200ResponseDataToJSON,
    ApiKeysPost200ResponseDataToJSONTyped,
} from './ApiKeysPost200ResponseData';

/**
 * 
 * @export
 * @interface ApiKeysPost200Response
 */
export interface ApiKeysPost200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ApiKeysPost200Response
     */
    success?: boolean;
    /**
     * 
     * @type {ApiKeysPost200ResponseData}
     * @memberof ApiKeysPost200Response
     */
    data?: ApiKeysPost200ResponseData;
}

/**
 * Check if a given object implements the ApiKeysPost200Response interface.
 */
export function instanceOfApiKeysPost200Response(value: object): value is ApiKeysPost200Response {
    return true;
}

export function ApiKeysPost200ResponseFromJSON(json: any): ApiKeysPost200Response {
    return ApiKeysPost200ResponseFromJSONTyped(json, false);
}

export function ApiKeysPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKeysPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'data': json['data'] == null ? undefined : ApiKeysPost200ResponseDataFromJSON(json['data']),
    };
}

export function ApiKeysPost200ResponseToJSON(json: any): ApiKeysPost200Response {
    return ApiKeysPost200ResponseToJSONTyped(json, false);
}

export function ApiKeysPost200ResponseToJSONTyped(value?: ApiKeysPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ApiKeysPost200ResponseDataToJSON(value['data']),
    };
}

