/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiKeysPostRequest
 */
export interface ApiKeysPostRequest {
    /**
     * Optional description for the API key
     * @type {string}
     * @memberof ApiKeysPostRequest
     */
    description?: string;
}

/**
 * Check if a given object implements the ApiKeysPostRequest interface.
 */
export function instanceOfApiKeysPostRequest(value: object): value is ApiKeysPostRequest {
    return true;
}

export function ApiKeysPostRequestFromJSON(json: any): ApiKeysPostRequest {
    return ApiKeysPostRequestFromJSONTyped(json, false);
}

export function ApiKeysPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKeysPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ApiKeysPostRequestToJSON(json: any): ApiKeysPostRequest {
    return ApiKeysPostRequestToJSONTyped(json, false);
}

export function ApiKeysPostRequestToJSONTyped(value?: ApiKeysPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
    };
}

