/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiKeysPost200ResponseData
 */
export interface ApiKeysPost200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof ApiKeysPost200ResponseData
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiKeysPost200ResponseData
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiKeysPost200ResponseData
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiKeysPost200ResponseData
     */
    description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApiKeysPost200ResponseData
     */
    isActive?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApiKeysPost200ResponseData
     */
    createdAt?: string;
}

/**
 * Check if a given object implements the ApiKeysPost200ResponseData interface.
 */
export function instanceOfApiKeysPost200ResponseData(value: object): value is ApiKeysPost200ResponseData {
    return true;
}

export function ApiKeysPost200ResponseDataFromJSON(json: any): ApiKeysPost200ResponseData {
    return ApiKeysPost200ResponseDataFromJSONTyped(json, false);
}

export function ApiKeysPost200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKeysPost200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'key': json['key'] == null ? undefined : json['key'],
        'description': json['description'] == null ? undefined : json['description'],
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
    };
}

export function ApiKeysPost200ResponseDataToJSON(json: any): ApiKeysPost200ResponseData {
    return ApiKeysPost200ResponseDataToJSONTyped(json, false);
}

export function ApiKeysPost200ResponseDataToJSONTyped(value?: ApiKeysPost200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'key': value['key'],
        'description': value['description'],
        'isActive': value['isActive'],
        'createdAt': value['createdAt'],
    };
}

