/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiKeysGet200ResponseApiKeysInner } from './ApiKeysGet200ResponseApiKeysInner';
import {
    ApiKeysGet200ResponseApiKeysInnerFromJSON,
    ApiKeysGet200ResponseApiKeysInnerFromJSONTyped,
    ApiKeysGet200ResponseApiKeysInnerToJSON,
    ApiKeysGet200ResponseApiKeysInnerToJSONTyped,
} from './ApiKeysGet200ResponseApiKeysInner';

/**
 * 
 * @export
 * @interface ApiKeysGet200Response
 */
export interface ApiKeysGet200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ApiKeysGet200Response
     */
    success?: boolean;
    /**
     * 
     * @type {Array<ApiKeysGet200ResponseApiKeysInner>}
     * @memberof ApiKeysGet200Response
     */
    apiKeys?: Array<ApiKeysGet200ResponseApiKeysInner>;
}

/**
 * Check if a given object implements the ApiKeysGet200Response interface.
 */
export function instanceOfApiKeysGet200Response(value: object): value is ApiKeysGet200Response {
    return true;
}

export function ApiKeysGet200ResponseFromJSON(json: any): ApiKeysGet200Response {
    return ApiKeysGet200ResponseFromJSONTyped(json, false);
}

export function ApiKeysGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKeysGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'apiKeys': json['apiKeys'] == null ? undefined : ((json['apiKeys'] as Array<any>).map(ApiKeysGet200ResponseApiKeysInnerFromJSON)),
    };
}

export function ApiKeysGet200ResponseToJSON(json: any): ApiKeysGet200Response {
    return ApiKeysGet200ResponseToJSONTyped(json, false);
}

export function ApiKeysGet200ResponseToJSONTyped(value?: ApiKeysGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'apiKeys': value['apiKeys'] == null ? undefined : ((value['apiKeys'] as Array<any>).map(ApiKeysGet200ResponseApiKeysInnerToJSON)),
    };
}

