/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthLogoutPost200Response
 */
export interface AuthLogoutPost200Response {
    /**
     * 
     * @type {boolean}
     * @memberof AuthLogoutPost200Response
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AuthLogoutPost200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the AuthLogoutPost200Response interface.
 */
export function instanceOfAuthLogoutPost200Response(value: object): value is AuthLogoutPost200Response {
    return true;
}

export function AuthLogoutPost200ResponseFromJSON(json: any): AuthLogoutPost200Response {
    return AuthLogoutPost200ResponseFromJSONTyped(json, false);
}

export function AuthLogoutPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLogoutPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function AuthLogoutPost200ResponseToJSON(json: any): AuthLogoutPost200Response {
    return AuthLogoutPost200ResponseToJSONTyped(json, false);
}

export function AuthLogoutPost200ResponseToJSONTyped(value?: AuthLogoutPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
    };
}

