/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthMeGet200ResponseBilling
 */
export interface AuthMeGet200ResponseBilling {
    /**
     * Whether the user has valid billing information set up in Polar
     * @type {boolean}
     * @memberof AuthMeGet200ResponseBilling
     */
    hasValidBilling: boolean;
    /**
     * Polar customer ID (if billing is set up)
     * @type {string}
     * @memberof AuthMeGet200ResponseBilling
     */
    customerId?: string;
    /**
     * Email associated with billing account
     * @type {string}
     * @memberof AuthMeGet200ResponseBilling
     */
    email?: string;
}

/**
 * Check if a given object implements the AuthMeGet200ResponseBilling interface.
 */
export function instanceOfAuthMeGet200ResponseBilling(value: object): value is AuthMeGet200ResponseBilling {
    if (!('hasValidBilling' in value) || value['hasValidBilling'] === undefined) return false;
    return true;
}

export function AuthMeGet200ResponseBillingFromJSON(json: any): AuthMeGet200ResponseBilling {
    return AuthMeGet200ResponseBillingFromJSONTyped(json, false);
}

export function AuthMeGet200ResponseBillingFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthMeGet200ResponseBilling {
    if (json == null) {
        return json;
    }
    return {
        
        'hasValidBilling': json['hasValidBilling'],
        'customerId': json['customerId'] == null ? undefined : json['customerId'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function AuthMeGet200ResponseBillingToJSON(json: any): AuthMeGet200ResponseBilling {
    return AuthMeGet200ResponseBillingToJSONTyped(json, false);
}

export function AuthMeGet200ResponseBillingToJSONTyped(value?: AuthMeGet200ResponseBilling | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hasValidBilling': value['hasValidBilling'],
        'customerId': value['customerId'],
        'email': value['email'],
    };
}

