/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthGithubCallbackGet200ResponseUser } from './AuthGithubCallbackGet200ResponseUser';
import {
    AuthGithubCallbackGet200ResponseUserFromJSON,
    AuthGithubCallbackGet200ResponseUserFromJSONTyped,
    AuthGithubCallbackGet200ResponseUserToJSON,
    AuthGithubCallbackGet200ResponseUserToJSONTyped,
} from './AuthGithubCallbackGet200ResponseUser';

/**
 * 
 * @export
 * @interface AuthGithubCallbackGet200Response
 */
export interface AuthGithubCallbackGet200Response {
    /**
     * 
     * @type {boolean}
     * @memberof AuthGithubCallbackGet200Response
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AuthGithubCallbackGet200Response
     */
    message?: string;
    /**
     * 
     * @type {AuthGithubCallbackGet200ResponseUser}
     * @memberof AuthGithubCallbackGet200Response
     */
    user?: AuthGithubCallbackGet200ResponseUser;
    /**
     * JWT token for authentication
     * @type {string}
     * @memberof AuthGithubCallbackGet200Response
     */
    token?: string;
}

/**
 * Check if a given object implements the AuthGithubCallbackGet200Response interface.
 */
export function instanceOfAuthGithubCallbackGet200Response(value: object): value is AuthGithubCallbackGet200Response {
    return true;
}

export function AuthGithubCallbackGet200ResponseFromJSON(json: any): AuthGithubCallbackGet200Response {
    return AuthGithubCallbackGet200ResponseFromJSONTyped(json, false);
}

export function AuthGithubCallbackGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthGithubCallbackGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'user': json['user'] == null ? undefined : AuthGithubCallbackGet200ResponseUserFromJSON(json['user']),
        'token': json['token'] == null ? undefined : json['token'],
    };
}

export function AuthGithubCallbackGet200ResponseToJSON(json: any): AuthGithubCallbackGet200Response {
    return AuthGithubCallbackGet200ResponseToJSONTyped(json, false);
}

export function AuthGithubCallbackGet200ResponseToJSONTyped(value?: AuthGithubCallbackGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'user': AuthGithubCallbackGet200ResponseUserToJSON(value['user']),
        'token': value['token'],
    };
}

