/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthMeGet200ResponseUser
 */
export interface AuthMeGet200ResponseUser {
    /**
     * 
     * @type {string}
     * @memberof AuthMeGet200ResponseUser
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthMeGet200ResponseUser
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthMeGet200ResponseUser
     */
    name?: string;
    /**
     * Current onboarding step completed
     * @type {number}
     * @memberof AuthMeGet200ResponseUser
     */
    onboardingStep?: number;
}

/**
 * Check if a given object implements the AuthMeGet200ResponseUser interface.
 */
export function instanceOfAuthMeGet200ResponseUser(value: object): value is AuthMeGet200ResponseUser {
    return true;
}

export function AuthMeGet200ResponseUserFromJSON(json: any): AuthMeGet200ResponseUser {
    return AuthMeGet200ResponseUserFromJSONTyped(json, false);
}

export function AuthMeGet200ResponseUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthMeGet200ResponseUser {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'email': json['email'] == null ? undefined : json['email'],
        'name': json['name'] == null ? undefined : json['name'],
        'onboardingStep': json['onboardingStep'] == null ? undefined : json['onboardingStep'],
    };
}

export function AuthMeGet200ResponseUserToJSON(json: any): AuthMeGet200ResponseUser {
    return AuthMeGet200ResponseUserToJSONTyped(json, false);
}

export function AuthMeGet200ResponseUserToJSONTyped(value?: AuthMeGet200ResponseUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'name': value['name'],
        'onboardingStep': value['onboardingStep'],
    };
}

