/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthMeGet200ResponseBilling } from './AuthMeGet200ResponseBilling';
import {
    AuthMeGet200ResponseBillingFromJSON,
    AuthMeGet200ResponseBillingFromJSONTyped,
    AuthMeGet200ResponseBillingToJSON,
    AuthMeGet200ResponseBillingToJSONTyped,
} from './AuthMeGet200ResponseBilling';
import type { AuthMeGet200ResponseUser } from './AuthMeGet200ResponseUser';
import {
    AuthMeGet200ResponseUserFromJSON,
    AuthMeGet200ResponseUserFromJSONTyped,
    AuthMeGet200ResponseUserToJSON,
    AuthMeGet200ResponseUserToJSONTyped,
} from './AuthMeGet200ResponseUser';

/**
 * 
 * @export
 * @interface AuthMeGet200Response
 */
export interface AuthMeGet200Response {
    /**
     * 
     * @type {boolean}
     * @memberof AuthMeGet200Response
     */
    success?: boolean;
    /**
     * 
     * @type {AuthMeGet200ResponseUser}
     * @memberof AuthMeGet200Response
     */
    user?: AuthMeGet200ResponseUser;
    /**
     * 
     * @type {AuthMeGet200ResponseBilling}
     * @memberof AuthMeGet200Response
     */
    billing?: AuthMeGet200ResponseBilling;
}

/**
 * Check if a given object implements the AuthMeGet200Response interface.
 */
export function instanceOfAuthMeGet200Response(value: object): value is AuthMeGet200Response {
    return true;
}

export function AuthMeGet200ResponseFromJSON(json: any): AuthMeGet200Response {
    return AuthMeGet200ResponseFromJSONTyped(json, false);
}

export function AuthMeGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthMeGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'user': json['user'] == null ? undefined : AuthMeGet200ResponseUserFromJSON(json['user']),
        'billing': json['billing'] == null ? undefined : AuthMeGet200ResponseBillingFromJSON(json['billing']),
    };
}

export function AuthMeGet200ResponseToJSON(json: any): AuthMeGet200Response {
    return AuthMeGet200ResponseToJSONTyped(json, false);
}

export function AuthMeGet200ResponseToJSONTyped(value?: AuthMeGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'user': AuthMeGet200ResponseUserToJSON(value['user']),
        'billing': AuthMeGet200ResponseBillingToJSON(value['billing']),
    };
}

