/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthGithubCallbackGet400Response
 */
export interface AuthGithubCallbackGet400Response {
    /**
     * 
     * @type {string}
     * @memberof AuthGithubCallbackGet400Response
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthGithubCallbackGet400Response
     */
    message?: string;
}

/**
 * Check if a given object implements the AuthGithubCallbackGet400Response interface.
 */
export function instanceOfAuthGithubCallbackGet400Response(value: object): value is AuthGithubCallbackGet400Response {
    return true;
}

export function AuthGithubCallbackGet400ResponseFromJSON(json: any): AuthGithubCallbackGet400Response {
    return AuthGithubCallbackGet400ResponseFromJSONTyped(json, false);
}

export function AuthGithubCallbackGet400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthGithubCallbackGet400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function AuthGithubCallbackGet400ResponseToJSON(json: any): AuthGithubCallbackGet400Response {
    return AuthGithubCallbackGet400ResponseToJSONTyped(json, false);
}

export function AuthGithubCallbackGet400ResponseToJSONTyped(value?: AuthGithubCallbackGet400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'message': value['message'],
    };
}

