/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DocumentsUsageStatsGet200ResponseStatsInner } from './DocumentsUsageStatsGet200ResponseStatsInner';
import {
    DocumentsUsageStatsGet200ResponseStatsInnerFromJSON,
    DocumentsUsageStatsGet200ResponseStatsInnerFromJSONTyped,
    DocumentsUsageStatsGet200ResponseStatsInnerToJSON,
    DocumentsUsageStatsGet200ResponseStatsInnerToJSONTyped,
} from './DocumentsUsageStatsGet200ResponseStatsInner';

/**
 * 
 * @export
 * @interface DocumentsUsageStatsGet200Response
 */
export interface DocumentsUsageStatsGet200Response {
    /**
     * 
     * @type {boolean}
     * @memberof DocumentsUsageStatsGet200Response
     */
    success?: boolean;
    /**
     * 
     * @type {Array<DocumentsUsageStatsGet200ResponseStatsInner>}
     * @memberof DocumentsUsageStatsGet200Response
     */
    stats?: Array<DocumentsUsageStatsGet200ResponseStatsInner>;
}

/**
 * Check if a given object implements the DocumentsUsageStatsGet200Response interface.
 */
export function instanceOfDocumentsUsageStatsGet200Response(value: object): value is DocumentsUsageStatsGet200Response {
    return true;
}

export function DocumentsUsageStatsGet200ResponseFromJSON(json: any): DocumentsUsageStatsGet200Response {
    return DocumentsUsageStatsGet200ResponseFromJSONTyped(json, false);
}

export function DocumentsUsageStatsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentsUsageStatsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'stats': json['stats'] == null ? undefined : ((json['stats'] as Array<any>).map(DocumentsUsageStatsGet200ResponseStatsInnerFromJSON)),
    };
}

export function DocumentsUsageStatsGet200ResponseToJSON(json: any): DocumentsUsageStatsGet200Response {
    return DocumentsUsageStatsGet200ResponseToJSONTyped(json, false);
}

export function DocumentsUsageStatsGet200ResponseToJSONTyped(value?: DocumentsUsageStatsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'stats': value['stats'] == null ? undefined : ((value['stats'] as Array<any>).map(DocumentsUsageStatsGet200ResponseStatsInnerToJSON)),
    };
}

