/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentsUsageStatsGet200ResponseStatsInner
 */
export interface DocumentsUsageStatsGet200ResponseStatsInner {
    /**
     * Date in YYYY-MM-DD format
     * @type {string}
     * @memberof DocumentsUsageStatsGet200ResponseStatsInner
     */
    date?: string;
    /**
     * Number of PDFs generated on this date
     * @type {number}
     * @memberof DocumentsUsageStatsGet200ResponseStatsInner
     */
    count?: number;
}

/**
 * Check if a given object implements the DocumentsUsageStatsGet200ResponseStatsInner interface.
 */
export function instanceOfDocumentsUsageStatsGet200ResponseStatsInner(value: object): value is DocumentsUsageStatsGet200ResponseStatsInner {
    return true;
}

export function DocumentsUsageStatsGet200ResponseStatsInnerFromJSON(json: any): DocumentsUsageStatsGet200ResponseStatsInner {
    return DocumentsUsageStatsGet200ResponseStatsInnerFromJSONTyped(json, false);
}

export function DocumentsUsageStatsGet200ResponseStatsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentsUsageStatsGet200ResponseStatsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : json['date'],
        'count': json['count'] == null ? undefined : json['count'],
    };
}

export function DocumentsUsageStatsGet200ResponseStatsInnerToJSON(json: any): DocumentsUsageStatsGet200ResponseStatsInner {
    return DocumentsUsageStatsGet200ResponseStatsInnerToJSONTyped(json, false);
}

export function DocumentsUsageStatsGet200ResponseStatsInnerToJSONTyped(value?: DocumentsUsageStatsGet200ResponseStatsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'],
        'count': value['count'],
    };
}

