/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Storage configuration for uploading the PDF
 * @export
 * @interface GeneratePostRequestStorage
 */
export interface GeneratePostRequestStorage {
    /**
     * Enable storage upload
     * @type {boolean}
     * @memberof GeneratePostRequestStorage
     */
    enabled?: boolean;
    /**
     * Storage configuration key
     * @type {string}
     * @memberof GeneratePostRequestStorage
     */
    storageKey?: string;
}

/**
 * Check if a given object implements the GeneratePostRequestStorage interface.
 */
export function instanceOfGeneratePostRequestStorage(value: object): value is GeneratePostRequestStorage {
    return true;
}

export function GeneratePostRequestStorageFromJSON(json: any): GeneratePostRequestStorage {
    return GeneratePostRequestStorageFromJSONTyped(json, false);
}

export function GeneratePostRequestStorageFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratePostRequestStorage {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'storageKey': json['storageKey'] == null ? undefined : json['storageKey'],
    };
}

export function GeneratePostRequestStorageToJSON(json: any): GeneratePostRequestStorage {
    return GeneratePostRequestStorageToJSONTyped(json, false);
}

export function GeneratePostRequestStorageToJSONTyped(value?: GeneratePostRequestStorage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enabled': value['enabled'],
        'storageKey': value['storageKey'],
    };
}

