/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeneratePost200Response
 */
export interface GeneratePost200Response {
    /**
     * Storage metadata if uploaded
     * @type {object}
     * @memberof GeneratePost200Response
     */
    meta?: object;
    /**
     * Base64 encoded PDF if returnFile is true
     * @type {string}
     * @memberof GeneratePost200Response
     */
    data?: string;
}

/**
 * Check if a given object implements the GeneratePost200Response interface.
 */
export function instanceOfGeneratePost200Response(value: object): value is GeneratePost200Response {
    return true;
}

export function GeneratePost200ResponseFromJSON(json: any): GeneratePost200Response {
    return GeneratePost200ResponseFromJSONTyped(json, false);
}

export function GeneratePost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratePost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'meta': json['meta'] == null ? undefined : json['meta'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function GeneratePost200ResponseToJSON(json: any): GeneratePost200Response {
    return GeneratePost200ResponseToJSONTyped(json, false);
}

export function GeneratePost200ResponseToJSONTyped(value?: GeneratePost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meta': value['meta'],
        'data': value['data'],
    };
}

