/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeneratePostRequestStorage } from './GeneratePostRequestStorage';
import {
    GeneratePostRequestStorageFromJSON,
    GeneratePostRequestStorageFromJSONTyped,
    GeneratePostRequestStorageToJSON,
    GeneratePostRequestStorageToJSONTyped,
} from './GeneratePostRequestStorage';

/**
 * 
 * @export
 * @interface GeneratePostRequest
 */
export interface GeneratePostRequest {
    /**
     * ID of stored template to use
     * @type {string}
     * @memberof GeneratePostRequest
     */
    templateId?: string;
    /**
     * Data to inject into the template
     * @type {object}
     * @memberof GeneratePostRequest
     */
    data?: object;
    /**
     * 
     * @type {GeneratePostRequestStorage}
     * @memberof GeneratePostRequest
     */
    storage?: GeneratePostRequestStorage;
    /**
     * If true, return PDF in response (default: true)
     * @type {boolean}
     * @memberof GeneratePostRequest
     */
    returnFile?: boolean;
    /**
     * If true, add SECRET watermark and charge 0 credits
     * @type {boolean}
     * @memberof GeneratePostRequest
     */
    sandbox?: boolean;
}

/**
 * Check if a given object implements the GeneratePostRequest interface.
 */
export function instanceOfGeneratePostRequest(value: object): value is GeneratePostRequest {
    return true;
}

export function GeneratePostRequestFromJSON(json: any): GeneratePostRequest {
    return GeneratePostRequestFromJSONTyped(json, false);
}

export function GeneratePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratePostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'templateId': json['templateId'] == null ? undefined : json['templateId'],
        'data': json['data'] == null ? undefined : json['data'],
        'storage': json['storage'] == null ? undefined : GeneratePostRequestStorageFromJSON(json['storage']),
        'returnFile': json['returnFile'] == null ? undefined : json['returnFile'],
        'sandbox': json['sandbox'] == null ? undefined : json['sandbox'],
    };
}

export function GeneratePostRequestToJSON(json: any): GeneratePostRequest {
    return GeneratePostRequestToJSONTyped(json, false);
}

export function GeneratePostRequestToJSONTyped(value?: GeneratePostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'templateId': value['templateId'],
        'data': value['data'],
        'storage': GeneratePostRequestStorageToJSON(value['storage']),
        'returnFile': value['returnFile'],
        'sandbox': value['sandbox'],
    };
}

