/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MeRecentActivityGet200ResponseRecentActivitiesInner } from './MeRecentActivityGet200ResponseRecentActivitiesInner';
import {
    MeRecentActivityGet200ResponseRecentActivitiesInnerFromJSON,
    MeRecentActivityGet200ResponseRecentActivitiesInnerFromJSONTyped,
    MeRecentActivityGet200ResponseRecentActivitiesInnerToJSON,
    MeRecentActivityGet200ResponseRecentActivitiesInnerToJSONTyped,
} from './MeRecentActivityGet200ResponseRecentActivitiesInner';
import type { MeRecentActivityGet200ResponseStats } from './MeRecentActivityGet200ResponseStats';
import {
    MeRecentActivityGet200ResponseStatsFromJSON,
    MeRecentActivityGet200ResponseStatsFromJSONTyped,
    MeRecentActivityGet200ResponseStatsToJSON,
    MeRecentActivityGet200ResponseStatsToJSONTyped,
} from './MeRecentActivityGet200ResponseStats';

/**
 * 
 * @export
 * @interface MeRecentActivityGet200Response
 */
export interface MeRecentActivityGet200Response {
    /**
     * 
     * @type {boolean}
     * @memberof MeRecentActivityGet200Response
     */
    success?: boolean;
    /**
     * 
     * @type {MeRecentActivityGet200ResponseStats}
     * @memberof MeRecentActivityGet200Response
     */
    stats?: MeRecentActivityGet200ResponseStats;
    /**
     * 
     * @type {Array<MeRecentActivityGet200ResponseRecentActivitiesInner>}
     * @memberof MeRecentActivityGet200Response
     */
    recentActivities?: Array<MeRecentActivityGet200ResponseRecentActivitiesInner>;
}

/**
 * Check if a given object implements the MeRecentActivityGet200Response interface.
 */
export function instanceOfMeRecentActivityGet200Response(value: object): value is MeRecentActivityGet200Response {
    return true;
}

export function MeRecentActivityGet200ResponseFromJSON(json: any): MeRecentActivityGet200Response {
    return MeRecentActivityGet200ResponseFromJSONTyped(json, false);
}

export function MeRecentActivityGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeRecentActivityGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'stats': json['stats'] == null ? undefined : MeRecentActivityGet200ResponseStatsFromJSON(json['stats']),
        'recentActivities': json['recentActivities'] == null ? undefined : ((json['recentActivities'] as Array<any>).map(MeRecentActivityGet200ResponseRecentActivitiesInnerFromJSON)),
    };
}

export function MeRecentActivityGet200ResponseToJSON(json: any): MeRecentActivityGet200Response {
    return MeRecentActivityGet200ResponseToJSONTyped(json, false);
}

export function MeRecentActivityGet200ResponseToJSONTyped(value?: MeRecentActivityGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'stats': MeRecentActivityGet200ResponseStatsToJSON(value['stats']),
        'recentActivities': value['recentActivities'] == null ? undefined : ((value['recentActivities'] as Array<any>).map(MeRecentActivityGet200ResponseRecentActivitiesInnerToJSON)),
    };
}

