/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MeRecentActivityGet200ResponseStats
 */
export interface MeRecentActivityGet200ResponseStats {
    /**
     * 
     * @type {number}
     * @memberof MeRecentActivityGet200ResponseStats
     */
    totalTemplates?: number;
    /**
     * 
     * @type {number}
     * @memberof MeRecentActivityGet200ResponseStats
     */
    totalActiveApiKeys?: number;
    /**
     * 
     * @type {number}
     * @memberof MeRecentActivityGet200ResponseStats
     */
    totalGeneratedPdfs?: number;
    /**
     * 
     * @type {number}
     * @memberof MeRecentActivityGet200ResponseStats
     */
    generatedPdfsLast30Days?: number;
    /**
     * 
     * @type {number}
     * @memberof MeRecentActivityGet200ResponseStats
     */
    totalCreditsUsed?: number;
    /**
     * Credits used in the current billing month
     * @type {number}
     * @memberof MeRecentActivityGet200ResponseStats
     */
    creditsUsedCurrentMonth?: number;
}

/**
 * Check if a given object implements the MeRecentActivityGet200ResponseStats interface.
 */
export function instanceOfMeRecentActivityGet200ResponseStats(value: object): value is MeRecentActivityGet200ResponseStats {
    return true;
}

export function MeRecentActivityGet200ResponseStatsFromJSON(json: any): MeRecentActivityGet200ResponseStats {
    return MeRecentActivityGet200ResponseStatsFromJSONTyped(json, false);
}

export function MeRecentActivityGet200ResponseStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeRecentActivityGet200ResponseStats {
    if (json == null) {
        return json;
    }
    return {
        
        'totalTemplates': json['totalTemplates'] == null ? undefined : json['totalTemplates'],
        'totalActiveApiKeys': json['totalActiveApiKeys'] == null ? undefined : json['totalActiveApiKeys'],
        'totalGeneratedPdfs': json['totalGeneratedPdfs'] == null ? undefined : json['totalGeneratedPdfs'],
        'generatedPdfsLast30Days': json['generatedPdfsLast30Days'] == null ? undefined : json['generatedPdfsLast30Days'],
        'totalCreditsUsed': json['totalCreditsUsed'] == null ? undefined : json['totalCreditsUsed'],
        'creditsUsedCurrentMonth': json['creditsUsedCurrentMonth'] == null ? undefined : json['creditsUsedCurrentMonth'],
    };
}

export function MeRecentActivityGet200ResponseStatsToJSON(json: any): MeRecentActivityGet200ResponseStats {
    return MeRecentActivityGet200ResponseStatsToJSONTyped(json, false);
}

export function MeRecentActivityGet200ResponseStatsToJSONTyped(value?: MeRecentActivityGet200ResponseStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalTemplates': value['totalTemplates'],
        'totalActiveApiKeys': value['totalActiveApiKeys'],
        'totalGeneratedPdfs': value['totalGeneratedPdfs'],
        'generatedPdfsLast30Days': value['generatedPdfsLast30Days'],
        'totalCreditsUsed': value['totalCreditsUsed'],
        'creditsUsedCurrentMonth': value['creditsUsedCurrentMonth'],
    };
}

