/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Storage configuration object
 * @export
 * @interface StorageConfigPostRequestStorageConfig
 */
export interface StorageConfigPostRequestStorageConfig {
    /**
     * Type of storage
     * @type {string}
     * @memberof StorageConfigPostRequestStorageConfig
     */
    storageType?: StorageConfigPostRequestStorageConfigStorageTypeEnum;
}


/**
 * @export
 */
export const StorageConfigPostRequestStorageConfigStorageTypeEnum = {
    S3: 's3',
    AzureBlob: 'azureBlob',
    Ftp: 'ftp'
} as const;
export type StorageConfigPostRequestStorageConfigStorageTypeEnum = typeof StorageConfigPostRequestStorageConfigStorageTypeEnum[keyof typeof StorageConfigPostRequestStorageConfigStorageTypeEnum];


/**
 * Check if a given object implements the StorageConfigPostRequestStorageConfig interface.
 */
export function instanceOfStorageConfigPostRequestStorageConfig(value: object): value is StorageConfigPostRequestStorageConfig {
    return true;
}

export function StorageConfigPostRequestStorageConfigFromJSON(json: any): StorageConfigPostRequestStorageConfig {
    return StorageConfigPostRequestStorageConfigFromJSONTyped(json, false);
}

export function StorageConfigPostRequestStorageConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageConfigPostRequestStorageConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'storageType': json['storageType'] == null ? undefined : json['storageType'],
    };
}

export function StorageConfigPostRequestStorageConfigToJSON(json: any): StorageConfigPostRequestStorageConfig {
    return StorageConfigPostRequestStorageConfigToJSONTyped(json, false);
}

export function StorageConfigPostRequestStorageConfigToJSONTyped(value?: StorageConfigPostRequestStorageConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'storageType': value['storageType'],
    };
}

