/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StorageConfigsGet200Response
 */
export interface StorageConfigsGet200Response {
    /**
     * 
     * @type {Array<string>}
     * @memberof StorageConfigsGet200Response
     */
    storageKeys?: Array<string>;
}

/**
 * Check if a given object implements the StorageConfigsGet200Response interface.
 */
export function instanceOfStorageConfigsGet200Response(value: object): value is StorageConfigsGet200Response {
    return true;
}

export function StorageConfigsGet200ResponseFromJSON(json: any): StorageConfigsGet200Response {
    return StorageConfigsGet200ResponseFromJSONTyped(json, false);
}

export function StorageConfigsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageConfigsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'storageKeys': json['storageKeys'] == null ? undefined : json['storageKeys'],
    };
}

export function StorageConfigsGet200ResponseToJSON(json: any): StorageConfigsGet200Response {
    return StorageConfigsGet200ResponseToJSONTyped(json, false);
}

export function StorageConfigsGet200ResponseToJSONTyped(value?: StorageConfigsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'storageKeys': value['storageKeys'],
    };
}

