/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StorageConfigStorageKeyGet200Response
 */
export interface StorageConfigStorageKeyGet200Response {
    /**
     * 
     * @type {object}
     * @memberof StorageConfigStorageKeyGet200Response
     */
    config?: object;
    /**
     * 
     * @type {string}
     * @memberof StorageConfigStorageKeyGet200Response
     */
    storageKey?: string;
}

/**
 * Check if a given object implements the StorageConfigStorageKeyGet200Response interface.
 */
export function instanceOfStorageConfigStorageKeyGet200Response(value: object): value is StorageConfigStorageKeyGet200Response {
    return true;
}

export function StorageConfigStorageKeyGet200ResponseFromJSON(json: any): StorageConfigStorageKeyGet200Response {
    return StorageConfigStorageKeyGet200ResponseFromJSONTyped(json, false);
}

export function StorageConfigStorageKeyGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageConfigStorageKeyGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : json['config'],
        'storageKey': json['storageKey'] == null ? undefined : json['storageKey'],
    };
}

export function StorageConfigStorageKeyGet200ResponseToJSON(json: any): StorageConfigStorageKeyGet200Response {
    return StorageConfigStorageKeyGet200ResponseToJSONTyped(json, false);
}

export function StorageConfigStorageKeyGet200ResponseToJSONTyped(value?: StorageConfigStorageKeyGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': value['config'],
        'storageKey': value['storageKey'],
    };
}

