/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StorageConfigPostRequestStorageConfig } from './StorageConfigPostRequestStorageConfig';
import {
    StorageConfigPostRequestStorageConfigFromJSON,
    StorageConfigPostRequestStorageConfigFromJSONTyped,
    StorageConfigPostRequestStorageConfigToJSON,
    StorageConfigPostRequestStorageConfigToJSONTyped,
} from './StorageConfigPostRequestStorageConfig';

/**
 * 
 * @export
 * @interface StorageConfigPostRequest
 */
export interface StorageConfigPostRequest {
    /**
     * Unique key for this storage configuration
     * @type {string}
     * @memberof StorageConfigPostRequest
     */
    storageKey: string;
    /**
     * 
     * @type {StorageConfigPostRequestStorageConfig}
     * @memberof StorageConfigPostRequest
     */
    storageConfig: StorageConfigPostRequestStorageConfig;
}

/**
 * Check if a given object implements the StorageConfigPostRequest interface.
 */
export function instanceOfStorageConfigPostRequest(value: object): value is StorageConfigPostRequest {
    if (!('storageKey' in value) || value['storageKey'] === undefined) return false;
    if (!('storageConfig' in value) || value['storageConfig'] === undefined) return false;
    return true;
}

export function StorageConfigPostRequestFromJSON(json: any): StorageConfigPostRequest {
    return StorageConfigPostRequestFromJSONTyped(json, false);
}

export function StorageConfigPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageConfigPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'storageKey': json['storageKey'],
        'storageConfig': StorageConfigPostRequestStorageConfigFromJSON(json['storageConfig']),
    };
}

export function StorageConfigPostRequestToJSON(json: any): StorageConfigPostRequest {
    return StorageConfigPostRequestToJSONTyped(json, false);
}

export function StorageConfigPostRequestToJSONTyped(value?: StorageConfigPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'storageKey': value['storageKey'],
        'storageConfig': StorageConfigPostRequestStorageConfigToJSON(value['storageConfig']),
    };
}

