/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StorageConfigStorageKeyPutRequest
 */
export interface StorageConfigStorageKeyPutRequest {
    /**
     * Type of storage
     * @type {string}
     * @memberof StorageConfigStorageKeyPutRequest
     */
    storageType: StorageConfigStorageKeyPutRequestStorageTypeEnum;
}


/**
 * @export
 */
export const StorageConfigStorageKeyPutRequestStorageTypeEnum = {
    S3: 's3',
    AzureBlob: 'azureBlob',
    Ftp: 'ftp'
} as const;
export type StorageConfigStorageKeyPutRequestStorageTypeEnum = typeof StorageConfigStorageKeyPutRequestStorageTypeEnum[keyof typeof StorageConfigStorageKeyPutRequestStorageTypeEnum];


/**
 * Check if a given object implements the StorageConfigStorageKeyPutRequest interface.
 */
export function instanceOfStorageConfigStorageKeyPutRequest(value: object): value is StorageConfigStorageKeyPutRequest {
    if (!('storageType' in value) || value['storageType'] === undefined) return false;
    return true;
}

export function StorageConfigStorageKeyPutRequestFromJSON(json: any): StorageConfigStorageKeyPutRequest {
    return StorageConfigStorageKeyPutRequestFromJSONTyped(json, false);
}

export function StorageConfigStorageKeyPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StorageConfigStorageKeyPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'storageType': json['storageType'],
    };
}

export function StorageConfigStorageKeyPutRequestToJSON(json: any): StorageConfigStorageKeyPutRequest {
    return StorageConfigStorageKeyPutRequestToJSONTyped(json, false);
}

export function StorageConfigStorageKeyPutRequestToJSONTyped(value?: StorageConfigStorageKeyPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'storageType': value['storageType'],
    };
}

