/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplatesPostRequest
 */
export interface TemplatesPostRequest {
    /**
     * HTML template content
     * @type {string}
     * @memberof TemplatesPostRequest
     */
    templateContent: string;
    /**
     * Name of the template
     * @type {string}
     * @memberof TemplatesPostRequest
     */
    templateName?: string;
}

/**
 * Check if a given object implements the TemplatesPostRequest interface.
 */
export function instanceOfTemplatesPostRequest(value: object): value is TemplatesPostRequest {
    if (!('templateContent' in value) || value['templateContent'] === undefined) return false;
    return true;
}

export function TemplatesPostRequestFromJSON(json: any): TemplatesPostRequest {
    return TemplatesPostRequestFromJSONTyped(json, false);
}

export function TemplatesPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatesPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'templateContent': json['templateContent'],
        'templateName': json['templateName'] == null ? undefined : json['templateName'],
    };
}

export function TemplatesPostRequestToJSON(json: any): TemplatesPostRequest {
    return TemplatesPostRequestToJSONTyped(json, false);
}

export function TemplatesPostRequestToJSONTyped(value?: TemplatesPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'templateContent': value['templateContent'],
        'templateName': value['templateName'],
    };
}

