/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TemplatesGet200ResponseTemplatesInner } from './TemplatesGet200ResponseTemplatesInner';
import {
    TemplatesGet200ResponseTemplatesInnerFromJSON,
    TemplatesGet200ResponseTemplatesInnerFromJSONTyped,
    TemplatesGet200ResponseTemplatesInnerToJSON,
    TemplatesGet200ResponseTemplatesInnerToJSONTyped,
} from './TemplatesGet200ResponseTemplatesInner';

/**
 * 
 * @export
 * @interface TemplatesGet200Response
 */
export interface TemplatesGet200Response {
    /**
     * 
     * @type {Array<TemplatesGet200ResponseTemplatesInner>}
     * @memberof TemplatesGet200Response
     */
    templates?: Array<TemplatesGet200ResponseTemplatesInner>;
}

/**
 * Check if a given object implements the TemplatesGet200Response interface.
 */
export function instanceOfTemplatesGet200Response(value: object): value is TemplatesGet200Response {
    return true;
}

export function TemplatesGet200ResponseFromJSON(json: any): TemplatesGet200Response {
    return TemplatesGet200ResponseFromJSONTyped(json, false);
}

export function TemplatesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatesGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'templates': json['templates'] == null ? undefined : ((json['templates'] as Array<any>).map(TemplatesGet200ResponseTemplatesInnerFromJSON)),
    };
}

export function TemplatesGet200ResponseToJSON(json: any): TemplatesGet200Response {
    return TemplatesGet200ResponseToJSONTyped(json, false);
}

export function TemplatesGet200ResponseToJSONTyped(value?: TemplatesGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'templates': value['templates'] == null ? undefined : ((value['templates'] as Array<any>).map(TemplatesGet200ResponseTemplatesInnerToJSON)),
    };
}

