/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplatesGenerateFromPromptPostRequest
 */
export interface TemplatesGenerateFromPromptPostRequest {
    /**
     * Description of the template you want to generate
     * @type {string}
     * @memberof TemplatesGenerateFromPromptPostRequest
     */
    prompt: string;
    /**
     * Data fields that will be injected into the template (keys will be used as placeholders)
     * @type {object}
     * @memberof TemplatesGenerateFromPromptPostRequest
     */
    params: object;
    /**
     * Name for the generated template
     * @type {string}
     * @memberof TemplatesGenerateFromPromptPostRequest
     */
    templateName?: string;
}

/**
 * Check if a given object implements the TemplatesGenerateFromPromptPostRequest interface.
 */
export function instanceOfTemplatesGenerateFromPromptPostRequest(value: object): value is TemplatesGenerateFromPromptPostRequest {
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    if (!('params' in value) || value['params'] === undefined) return false;
    return true;
}

export function TemplatesGenerateFromPromptPostRequestFromJSON(json: any): TemplatesGenerateFromPromptPostRequest {
    return TemplatesGenerateFromPromptPostRequestFromJSONTyped(json, false);
}

export function TemplatesGenerateFromPromptPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatesGenerateFromPromptPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'prompt': json['prompt'],
        'params': json['params'],
        'templateName': json['templateName'] == null ? undefined : json['templateName'],
    };
}

export function TemplatesGenerateFromPromptPostRequestToJSON(json: any): TemplatesGenerateFromPromptPostRequest {
    return TemplatesGenerateFromPromptPostRequestToJSONTyped(json, false);
}

export function TemplatesGenerateFromPromptPostRequestToJSONTyped(value?: TemplatesGenerateFromPromptPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prompt': value['prompt'],
        'params': value['params'],
        'templateName': value['templateName'],
    };
}

