/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplatesGenerateFromPdfPost500Response
 */
export interface TemplatesGenerateFromPdfPost500Response {
    /**
     * 
     * @type {string}
     * @memberof TemplatesGenerateFromPdfPost500Response
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof TemplatesGenerateFromPdfPost500Response
     */
    details?: string;
}

/**
 * Check if a given object implements the TemplatesGenerateFromPdfPost500Response interface.
 */
export function instanceOfTemplatesGenerateFromPdfPost500Response(value: object): value is TemplatesGenerateFromPdfPost500Response {
    return true;
}

export function TemplatesGenerateFromPdfPost500ResponseFromJSON(json: any): TemplatesGenerateFromPdfPost500Response {
    return TemplatesGenerateFromPdfPost500ResponseFromJSONTyped(json, false);
}

export function TemplatesGenerateFromPdfPost500ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatesGenerateFromPdfPost500Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
        'details': json['details'] == null ? undefined : json['details'],
    };
}

export function TemplatesGenerateFromPdfPost500ResponseToJSON(json: any): TemplatesGenerateFromPdfPost500Response {
    return TemplatesGenerateFromPdfPost500ResponseToJSONTyped(json, false);
}

export function TemplatesGenerateFromPdfPost500ResponseToJSONTyped(value?: TemplatesGenerateFromPdfPost500Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'details': value['details'],
    };
}

