/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplatesTemplateIdPutRequest
 */
export interface TemplatesTemplateIdPutRequest {
    /**
     * HTML template content
     * @type {string}
     * @memberof TemplatesTemplateIdPutRequest
     */
    templateContent?: string;
    /**
     * Name of the template
     * @type {string}
     * @memberof TemplatesTemplateIdPutRequest
     */
    templateName?: string;
}

/**
 * Check if a given object implements the TemplatesTemplateIdPutRequest interface.
 */
export function instanceOfTemplatesTemplateIdPutRequest(value: object): value is TemplatesTemplateIdPutRequest {
    return true;
}

export function TemplatesTemplateIdPutRequestFromJSON(json: any): TemplatesTemplateIdPutRequest {
    return TemplatesTemplateIdPutRequestFromJSONTyped(json, false);
}

export function TemplatesTemplateIdPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatesTemplateIdPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'templateContent': json['templateContent'] == null ? undefined : json['templateContent'],
        'templateName': json['templateName'] == null ? undefined : json['templateName'],
    };
}

export function TemplatesTemplateIdPutRequestToJSON(json: any): TemplatesTemplateIdPutRequest {
    return TemplatesTemplateIdPutRequestToJSONTyped(json, false);
}

export function TemplatesTemplateIdPutRequestToJSONTyped(value?: TemplatesTemplateIdPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'templateContent': value['templateContent'],
        'templateName': value['templateName'],
    };
}

