/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplatesPost400Response
 */
export interface TemplatesPost400Response {
    /**
     * 
     * @type {string}
     * @memberof TemplatesPost400Response
     */
    error?: string;
}

/**
 * Check if a given object implements the TemplatesPost400Response interface.
 */
export function instanceOfTemplatesPost400Response(value: object): value is TemplatesPost400Response {
    return true;
}

export function TemplatesPost400ResponseFromJSON(json: any): TemplatesPost400Response {
    return TemplatesPost400ResponseFromJSONTyped(json, false);
}

export function TemplatesPost400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatesPost400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function TemplatesPost400ResponseToJSON(json: any): TemplatesPost400Response {
    return TemplatesPost400ResponseToJSONTyped(json, false);
}

export function TemplatesPost400ResponseToJSONTyped(value?: TemplatesPost400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

