/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TemplatesGet200ResponseTemplatesInner } from './TemplatesGet200ResponseTemplatesInner';
import {
    TemplatesGet200ResponseTemplatesInnerFromJSON,
    TemplatesGet200ResponseTemplatesInnerFromJSONTyped,
    TemplatesGet200ResponseTemplatesInnerToJSON,
    TemplatesGet200ResponseTemplatesInnerToJSONTyped,
} from './TemplatesGet200ResponseTemplatesInner';

/**
 * 
 * @export
 * @interface TemplatesPost200Response
 */
export interface TemplatesPost200Response {
    /**
     * 
     * @type {boolean}
     * @memberof TemplatesPost200Response
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TemplatesPost200Response
     */
    message?: string;
    /**
     * 
     * @type {TemplatesGet200ResponseTemplatesInner}
     * @memberof TemplatesPost200Response
     */
    data?: TemplatesGet200ResponseTemplatesInner;
}

/**
 * Check if a given object implements the TemplatesPost200Response interface.
 */
export function instanceOfTemplatesPost200Response(value: object): value is TemplatesPost200Response {
    return true;
}

export function TemplatesPost200ResponseFromJSON(json: any): TemplatesPost200Response {
    return TemplatesPost200ResponseFromJSONTyped(json, false);
}

export function TemplatesPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatesPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : TemplatesGet200ResponseTemplatesInnerFromJSON(json['data']),
    };
}

export function TemplatesPost200ResponseToJSON(json: any): TemplatesPost200Response {
    return TemplatesPost200ResponseToJSONTyped(json, false);
}

export function TemplatesPost200ResponseToJSONTyped(value?: TemplatesPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': TemplatesGet200ResponseTemplatesInnerToJSON(value['data']),
    };
}

