/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiKeysGet200Response,
  ApiKeysPost200Response,
  ApiKeysPostRequest,
  AuthGithubCallbackGet400Response,
  AuthLogoutPost200Response,
} from '../models/index';
import {
    ApiKeysGet200ResponseFromJSON,
    ApiKeysGet200ResponseToJSON,
    ApiKeysPost200ResponseFromJSON,
    ApiKeysPost200ResponseToJSON,
    ApiKeysPostRequestFromJSON,
    ApiKeysPostRequestToJSON,
    AuthGithubCallbackGet400ResponseFromJSON,
    AuthGithubCallbackGet400ResponseToJSON,
    AuthLogoutPost200ResponseFromJSON,
    AuthLogoutPost200ResponseToJSON,
} from '../models/index';

export interface ApiKeysIdDeactivatePutRequest {
    id: string;
}

export interface ApiKeysPostOperationRequest {
    apiKeysPostRequest?: ApiKeysPostRequest;
}

/**
 * 
 */
export class APIKeysApi extends runtime.BaseAPI {

    /**
     * List all API keys for authenticated user
     */
    async apiKeysGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiKeysGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api-keys`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiKeysGet200ResponseFromJSON(jsonValue));
    }

    /**
     * List all API keys for authenticated user
     */
    async apiKeysGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiKeysGet200Response> {
        const response = await this.apiKeysGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Deactivate an API key
     */
    async apiKeysIdDeactivatePutRaw(requestParameters: ApiKeysIdDeactivatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthLogoutPost200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiKeysIdDeactivatePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api-keys/{id}/deactivate`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthLogoutPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Deactivate an API key
     */
    async apiKeysIdDeactivatePut(requestParameters: ApiKeysIdDeactivatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthLogoutPost200Response> {
        const response = await this.apiKeysIdDeactivatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new API key
     */
    async apiKeysPostRaw(requestParameters: ApiKeysPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiKeysPost200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api-keys`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiKeysPostRequestToJSON(requestParameters['apiKeysPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiKeysPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Create a new API key
     */
    async apiKeysPost(requestParameters: ApiKeysPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiKeysPost200Response> {
        const response = await this.apiKeysPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
