/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthBillingGet200Response,
  AuthCheckoutPost200Response,
  AuthCreditsGet200Response,
  AuthGithubCallbackGet200Response,
  AuthGithubCallbackGet400Response,
  AuthInvoicesGet200Response,
  AuthInvoicesInvoiceIdGet200Response,
  AuthLogoutPost200Response,
  AuthMeGet200Response,
  AuthOnboardingStepPutRequest,
  MeRecentActivityGet200Response,
} from '../models/index';
import {
    AuthBillingGet200ResponseFromJSON,
    AuthBillingGet200ResponseToJSON,
    AuthCheckoutPost200ResponseFromJSON,
    AuthCheckoutPost200ResponseToJSON,
    AuthCreditsGet200ResponseFromJSON,
    AuthCreditsGet200ResponseToJSON,
    AuthGithubCallbackGet200ResponseFromJSON,
    AuthGithubCallbackGet200ResponseToJSON,
    AuthGithubCallbackGet400ResponseFromJSON,
    AuthGithubCallbackGet400ResponseToJSON,
    AuthInvoicesGet200ResponseFromJSON,
    AuthInvoicesGet200ResponseToJSON,
    AuthInvoicesInvoiceIdGet200ResponseFromJSON,
    AuthInvoicesInvoiceIdGet200ResponseToJSON,
    AuthLogoutPost200ResponseFromJSON,
    AuthLogoutPost200ResponseToJSON,
    AuthMeGet200ResponseFromJSON,
    AuthMeGet200ResponseToJSON,
    AuthOnboardingStepPutRequestFromJSON,
    AuthOnboardingStepPutRequestToJSON,
    MeRecentActivityGet200ResponseFromJSON,
    MeRecentActivityGet200ResponseToJSON,
} from '../models/index';

export interface AuthBillingGetRequest {
    userId: string;
}

export interface AuthGithubCallbackGetRequest {
    code?: string;
    state?: string;
    error?: string;
    errorDescription?: string;
}

export interface AuthInvoicesGetRequest {
    page?: number;
    limit?: number;
}

export interface AuthInvoicesInvoiceIdGetRequest {
    invoiceId: string;
}

export interface AuthOnboardingStepPutOperationRequest {
    authOnboardingStepPutRequest: AuthOnboardingStepPutRequest;
}

/**
 * 
 */
export class AuthenticationApi extends runtime.BaseAPI {

    /**
     * Get customer portal URL for managing payment details in Polar
     */
    async authBillingGetRaw(requestParameters: AuthBillingGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthBillingGet200Response>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling authBillingGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/billing`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthBillingGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Get customer portal URL for managing payment details in Polar
     */
    async authBillingGet(requestParameters: AuthBillingGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthBillingGet200Response> {
        const response = await this.authBillingGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a Polar checkout session URL for subscription
     */
    async authCheckoutPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthCheckoutPost200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/checkout`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthCheckoutPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Create a Polar checkout session URL for subscription
     */
    async authCheckoutPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthCheckoutPost200Response> {
        const response = await this.authCheckoutPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get user credit usage and subscription status
     */
    async authCreditsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthCreditsGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/credits`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthCreditsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Get user credit usage and subscription status
     */
    async authCreditsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthCreditsGet200Response> {
        const response = await this.authCreditsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * GitHub OAuth callback endpoint
     */
    async authGithubCallbackGetRaw(requestParameters: AuthGithubCallbackGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthGithubCallbackGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['code'] != null) {
            queryParameters['code'] = requestParameters['code'];
        }

        if (requestParameters['state'] != null) {
            queryParameters['state'] = requestParameters['state'];
        }

        if (requestParameters['error'] != null) {
            queryParameters['error'] = requestParameters['error'];
        }

        if (requestParameters['errorDescription'] != null) {
            queryParameters['error_description'] = requestParameters['errorDescription'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/github/callback`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthGithubCallbackGet200ResponseFromJSON(jsonValue));
    }

    /**
     * GitHub OAuth callback endpoint
     */
    async authGithubCallbackGet(requestParameters: AuthGithubCallbackGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthGithubCallbackGet200Response> {
        const response = await this.authGithubCallbackGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List previous invoices from Polar
     */
    async authInvoicesGetRaw(requestParameters: AuthInvoicesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthInvoicesGet200Response>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/invoices`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthInvoicesGet200ResponseFromJSON(jsonValue));
    }

    /**
     * List previous invoices from Polar
     */
    async authInvoicesGet(requestParameters: AuthInvoicesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthInvoicesGet200Response> {
        const response = await this.authInvoicesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a specific invoice URL from Polar
     */
    async authInvoicesInvoiceIdGetRaw(requestParameters: AuthInvoicesInvoiceIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthInvoicesInvoiceIdGet200Response>> {
        if (requestParameters['invoiceId'] == null) {
            throw new runtime.RequiredError(
                'invoiceId',
                'Required parameter "invoiceId" was null or undefined when calling authInvoicesInvoiceIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/invoices/{invoiceId}`;
        urlPath = urlPath.replace(`{${"invoiceId"}}`, encodeURIComponent(String(requestParameters['invoiceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthInvoicesInvoiceIdGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Get a specific invoice URL from Polar
     */
    async authInvoicesInvoiceIdGet(requestParameters: AuthInvoicesInvoiceIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthInvoicesInvoiceIdGet200Response> {
        const response = await this.authInvoicesInvoiceIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Logout and clear authentication cookie
     */
    async authLogoutPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthLogoutPost200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/logout`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthLogoutPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Logout and clear authentication cookie
     */
    async authLogoutPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthLogoutPost200Response> {
        const response = await this.authLogoutPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get current authenticated user information with billing status
     */
    async authMeGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthMeGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/me`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthMeGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Get current authenticated user information with billing status
     */
    async authMeGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthMeGet200Response> {
        const response = await this.authMeGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update the onboarding step for the authenticated user
     */
    async authOnboardingStepPutRaw(requestParameters: AuthOnboardingStepPutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthLogoutPost200Response>> {
        if (requestParameters['authOnboardingStepPutRequest'] == null) {
            throw new runtime.RequiredError(
                'authOnboardingStepPutRequest',
                'Required parameter "authOnboardingStepPutRequest" was null or undefined when calling authOnboardingStepPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/auth/onboarding-step`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AuthOnboardingStepPutRequestToJSON(requestParameters['authOnboardingStepPutRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthLogoutPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Update the onboarding step for the authenticated user
     */
    async authOnboardingStepPut(requestParameters: AuthOnboardingStepPutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthLogoutPost200Response> {
        const response = await this.authOnboardingStepPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get user statistics and recent activity
     */
    async meRecentActivityGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MeRecentActivityGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/me/recent-activity`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MeRecentActivityGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Get user statistics and recent activity
     */
    async meRecentActivityGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MeRecentActivityGet200Response> {
        const response = await this.meRecentActivityGetRaw(initOverrides);
        return await response.value();
    }

}
