/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DocumentsUsageStatsGet200Response,
  GeneratePost200Response,
  GeneratePostRequest,
  TemplatesPost400Response,
} from '../models/index';
import {
    DocumentsUsageStatsGet200ResponseFromJSON,
    DocumentsUsageStatsGet200ResponseToJSON,
    GeneratePost200ResponseFromJSON,
    GeneratePost200ResponseToJSON,
    GeneratePostRequestFromJSON,
    GeneratePostRequestToJSON,
    TemplatesPost400ResponseFromJSON,
    TemplatesPost400ResponseToJSON,
} from '../models/index';

export interface GeneratePostOperationRequest {
    generatePostRequest?: GeneratePostRequest;
}

/**
 * 
 */
export class DocumentsApi extends runtime.BaseAPI {

    /**
     * Get document generation usage statistics for the last 7 days
     */
    async documentsUsageStatsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DocumentsUsageStatsGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/documents/usage-stats`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DocumentsUsageStatsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Get document generation usage statistics for the last 7 days
     */
    async documentsUsageStatsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DocumentsUsageStatsGet200Response> {
        const response = await this.documentsUsageStatsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Generate a PDF document from a template
     */
    async generatePostRaw(requestParameters: GeneratePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GeneratePost200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/generate`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GeneratePostRequestToJSON(requestParameters['generatePostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GeneratePost200ResponseFromJSON(jsonValue));
    }

    /**
     * Generate a PDF document from a template
     */
    async generatePost(requestParameters: GeneratePostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GeneratePost200Response> {
        const response = await this.generatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
