/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthLogoutPost200Response,
  StorageConfigPostRequest,
  StorageConfigStorageKeyGet200Response,
  StorageConfigStorageKeyPutRequest,
  StorageConfigsGet200Response,
  TemplatesPost400Response,
} from '../models/index';
import {
    AuthLogoutPost200ResponseFromJSON,
    AuthLogoutPost200ResponseToJSON,
    StorageConfigPostRequestFromJSON,
    StorageConfigPostRequestToJSON,
    StorageConfigStorageKeyGet200ResponseFromJSON,
    StorageConfigStorageKeyGet200ResponseToJSON,
    StorageConfigStorageKeyPutRequestFromJSON,
    StorageConfigStorageKeyPutRequestToJSON,
    StorageConfigsGet200ResponseFromJSON,
    StorageConfigsGet200ResponseToJSON,
    TemplatesPost400ResponseFromJSON,
    TemplatesPost400ResponseToJSON,
} from '../models/index';

export interface StorageConfigPostOperationRequest {
    storageConfigPostRequest: StorageConfigPostRequest;
}

export interface StorageConfigStorageKeyDeleteRequest {
    storageKey: string;
}

export interface StorageConfigStorageKeyGetRequest {
    storageKey: string;
}

export interface StorageConfigStorageKeyPutOperationRequest {
    storageKey: string;
    storageConfigStorageKeyPutRequest: StorageConfigStorageKeyPutRequest;
}

/**
 * 
 */
export class StorageApi extends runtime.BaseAPI {

    /**
     * Create a new storage configuration
     */
    async storageConfigPostRaw(requestParameters: StorageConfigPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthLogoutPost200Response>> {
        if (requestParameters['storageConfigPostRequest'] == null) {
            throw new runtime.RequiredError(
                'storageConfigPostRequest',
                'Required parameter "storageConfigPostRequest" was null or undefined when calling storageConfigPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/storage-config`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StorageConfigPostRequestToJSON(requestParameters['storageConfigPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthLogoutPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Create a new storage configuration
     */
    async storageConfigPost(requestParameters: StorageConfigPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthLogoutPost200Response> {
        const response = await this.storageConfigPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a storage configuration
     */
    async storageConfigStorageKeyDeleteRaw(requestParameters: StorageConfigStorageKeyDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthLogoutPost200Response>> {
        if (requestParameters['storageKey'] == null) {
            throw new runtime.RequiredError(
                'storageKey',
                'Required parameter "storageKey" was null or undefined when calling storageConfigStorageKeyDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/storage-config/{storageKey}`;
        urlPath = urlPath.replace(`{${"storageKey"}}`, encodeURIComponent(String(requestParameters['storageKey'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthLogoutPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Delete a storage configuration
     */
    async storageConfigStorageKeyDelete(requestParameters: StorageConfigStorageKeyDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthLogoutPost200Response> {
        const response = await this.storageConfigStorageKeyDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a storage configuration by key
     */
    async storageConfigStorageKeyGetRaw(requestParameters: StorageConfigStorageKeyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StorageConfigStorageKeyGet200Response>> {
        if (requestParameters['storageKey'] == null) {
            throw new runtime.RequiredError(
                'storageKey',
                'Required parameter "storageKey" was null or undefined when calling storageConfigStorageKeyGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/storage-config/{storageKey}`;
        urlPath = urlPath.replace(`{${"storageKey"}}`, encodeURIComponent(String(requestParameters['storageKey'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StorageConfigStorageKeyGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Get a storage configuration by key
     */
    async storageConfigStorageKeyGet(requestParameters: StorageConfigStorageKeyGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StorageConfigStorageKeyGet200Response> {
        const response = await this.storageConfigStorageKeyGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a storage configuration
     */
    async storageConfigStorageKeyPutRaw(requestParameters: StorageConfigStorageKeyPutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthLogoutPost200Response>> {
        if (requestParameters['storageKey'] == null) {
            throw new runtime.RequiredError(
                'storageKey',
                'Required parameter "storageKey" was null or undefined when calling storageConfigStorageKeyPut().'
            );
        }

        if (requestParameters['storageConfigStorageKeyPutRequest'] == null) {
            throw new runtime.RequiredError(
                'storageConfigStorageKeyPutRequest',
                'Required parameter "storageConfigStorageKeyPutRequest" was null or undefined when calling storageConfigStorageKeyPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/storage-config/{storageKey}`;
        urlPath = urlPath.replace(`{${"storageKey"}}`, encodeURIComponent(String(requestParameters['storageKey'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: StorageConfigStorageKeyPutRequestToJSON(requestParameters['storageConfigStorageKeyPutRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthLogoutPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Update a storage configuration
     */
    async storageConfigStorageKeyPut(requestParameters: StorageConfigStorageKeyPutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthLogoutPost200Response> {
        const response = await this.storageConfigStorageKeyPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all storage configurations
     */
    async storageConfigsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StorageConfigsGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/storage-configs`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StorageConfigsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * List all storage configurations
     */
    async storageConfigsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StorageConfigsGet200Response> {
        const response = await this.storageConfigsGetRaw(initOverrides);
        return await response.value();
    }

}
