/* tslint:disable */
/* eslint-disable */
/**
 * Secret PDF API
 * API for generating PDFs from HTML templates with AI assistance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthLogoutPost200Response,
  TemplatesGenerateFromPdfPost500Response,
  TemplatesGenerateFromPromptPostRequest,
  TemplatesGet200Response,
  TemplatesGet200ResponseTemplatesInner,
  TemplatesPost200Response,
  TemplatesPost400Response,
  TemplatesPostRequest,
  TemplatesTemplateIdPutRequest,
} from '../models/index';
import {
    AuthLogoutPost200ResponseFromJSON,
    AuthLogoutPost200ResponseToJSON,
    TemplatesGenerateFromPdfPost500ResponseFromJSON,
    TemplatesGenerateFromPdfPost500ResponseToJSON,
    TemplatesGenerateFromPromptPostRequestFromJSON,
    TemplatesGenerateFromPromptPostRequestToJSON,
    TemplatesGet200ResponseFromJSON,
    TemplatesGet200ResponseToJSON,
    TemplatesGet200ResponseTemplatesInnerFromJSON,
    TemplatesGet200ResponseTemplatesInnerToJSON,
    TemplatesPost200ResponseFromJSON,
    TemplatesPost200ResponseToJSON,
    TemplatesPost400ResponseFromJSON,
    TemplatesPost400ResponseToJSON,
    TemplatesPostRequestFromJSON,
    TemplatesPostRequestToJSON,
    TemplatesTemplateIdPutRequestFromJSON,
    TemplatesTemplateIdPutRequestToJSON,
} from '../models/index';

export interface TemplatesGenerateFromPdfPostRequest {
    file: Blob;
}

export interface TemplatesGenerateFromPromptPostOperationRequest {
    templatesGenerateFromPromptPostRequest: TemplatesGenerateFromPromptPostRequest;
}

export interface TemplatesPostOperationRequest {
    templatesPostRequest: TemplatesPostRequest;
}

export interface TemplatesTemplateIdDeleteRequest {
    templateId: string;
}

export interface TemplatesTemplateIdGetRequest {
    templateId: string;
}

export interface TemplatesTemplateIdPutOperationRequest {
    templateId: string;
    templatesTemplateIdPutRequest?: TemplatesTemplateIdPutRequest;
}

/**
 * 
 */
export class TemplatesApi extends runtime.BaseAPI {

    /**
     * Generate HTML template from PDF file using AI. Upload a PDF file using multipart/form-data with field name \"file\". The generated template will be automatically saved to the database.
     */
    async templatesGenerateFromPdfPostRaw(requestParameters: TemplatesGenerateFromPdfPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatesPost200Response>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling templatesGenerateFromPdfPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/templates/generate-from-pdf`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplatesPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Generate HTML template from PDF file using AI. Upload a PDF file using multipart/form-data with field name \"file\". The generated template will be automatically saved to the database.
     */
    async templatesGenerateFromPdfPost(requestParameters: TemplatesGenerateFromPdfPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatesPost200Response> {
        const response = await this.templatesGenerateFromPdfPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generate HTML template from AI prompt. Provide a description of the template you want and the data fields to inject.
     */
    async templatesGenerateFromPromptPostRaw(requestParameters: TemplatesGenerateFromPromptPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatesPost200Response>> {
        if (requestParameters['templatesGenerateFromPromptPostRequest'] == null) {
            throw new runtime.RequiredError(
                'templatesGenerateFromPromptPostRequest',
                'Required parameter "templatesGenerateFromPromptPostRequest" was null or undefined when calling templatesGenerateFromPromptPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/templates/generate-from-prompt`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TemplatesGenerateFromPromptPostRequestToJSON(requestParameters['templatesGenerateFromPromptPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplatesPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Generate HTML template from AI prompt. Provide a description of the template you want and the data fields to inject.
     */
    async templatesGenerateFromPromptPost(requestParameters: TemplatesGenerateFromPromptPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatesPost200Response> {
        const response = await this.templatesGenerateFromPromptPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all templates for authenticated user
     */
    async templatesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatesGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/templates`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplatesGet200ResponseFromJSON(jsonValue));
    }

    /**
     * List all templates for authenticated user
     */
    async templatesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatesGet200Response> {
        const response = await this.templatesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Create a new HTML template
     */
    async templatesPostRaw(requestParameters: TemplatesPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatesPost200Response>> {
        if (requestParameters['templatesPostRequest'] == null) {
            throw new runtime.RequiredError(
                'templatesPostRequest',
                'Required parameter "templatesPostRequest" was null or undefined when calling templatesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/templates`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TemplatesPostRequestToJSON(requestParameters['templatesPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplatesPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Create a new HTML template
     */
    async templatesPost(requestParameters: TemplatesPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatesPost200Response> {
        const response = await this.templatesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a template
     */
    async templatesTemplateIdDeleteRaw(requestParameters: TemplatesTemplateIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthLogoutPost200Response>> {
        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling templatesTemplateIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/templates/{templateId}`;
        urlPath = urlPath.replace(`{${"templateId"}}`, encodeURIComponent(String(requestParameters['templateId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthLogoutPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Delete a template
     */
    async templatesTemplateIdDelete(requestParameters: TemplatesTemplateIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthLogoutPost200Response> {
        const response = await this.templatesTemplateIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a template by ID
     */
    async templatesTemplateIdGetRaw(requestParameters: TemplatesTemplateIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatesGet200ResponseTemplatesInner>> {
        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling templatesTemplateIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/templates/{templateId}`;
        urlPath = urlPath.replace(`{${"templateId"}}`, encodeURIComponent(String(requestParameters['templateId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplatesGet200ResponseTemplatesInnerFromJSON(jsonValue));
    }

    /**
     * Get a template by ID
     */
    async templatesTemplateIdGet(requestParameters: TemplatesTemplateIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatesGet200ResponseTemplatesInner> {
        const response = await this.templatesTemplateIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a template
     */
    async templatesTemplateIdPutRaw(requestParameters: TemplatesTemplateIdPutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatesPost200Response>> {
        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling templatesTemplateIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-API-Key"] = await this.configuration.apiKey("X-API-Key"); // apiKey authentication
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/templates/{templateId}`;
        urlPath = urlPath.replace(`{${"templateId"}}`, encodeURIComponent(String(requestParameters['templateId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TemplatesTemplateIdPutRequestToJSON(requestParameters['templatesTemplateIdPutRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplatesPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Update a template
     */
    async templatesTemplateIdPut(requestParameters: TemplatesTemplateIdPutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatesPost200Response> {
        const response = await this.templatesTemplateIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
